### ISSUE TITLE
爬出来的json数据无法解析

### ISSUE THREAD

**Issue by Heisenbean** [Nymphet/t66y-spider#1]
首先谢谢作者的爬虫.
今天试着爬了达盖尔板块的数据,发现爬到的json数据无法解析,一个一个改比较麻烦,还是希望作者有时间看下.

**Comment by Nymphet** [comment]
Thanks for your report. Scrapy 自带的序列化输出似乎不是标准格式的 jsonline，而是 `[json1, json2, json3, ...]` 的形式。可以试试用 python 的 ast.literal_eval 先读取到 list，然后再对 list 中的元素一个个 json.load
